# Generated by Django 5.2.9 on 2026-01-03 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmodel',
            old_name='Email',
            new_name='email',
        ),
    ]
